version: "2"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam

linters-settings:
  goimports:
    local-prefixes: github.com/gyaneshwarpardhi/ifttt

issues:
  exclude-rules:
    # Test files: allow unused function parameters and unhandled errors
    - path: _test\.go
      linters:
        - errcheck
        - unparam
  max-issues-per-linter: 50
  max-same-issues: 10
