name: Bug Report
description: Something is not working as expected
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to file a bug report. Please fill out the sections below as completely as possible.

  - type: input
    id: go-version
    attributes:
      label: Go version
      description: Output of `go version`
      placeholder: "go version go1.23 darwin/arm64"
    validations:
      required: true

  - type: input
    id: engine-version
    attributes:
      label: Engine version / commit
      description: Git tag or commit SHA
      placeholder: "v0.1.0 or abc1234"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: |
        Include the minimal YAML config and curl command (or test) that demonstrates the bug.
      placeholder: |
        1. configs/rules.yaml:
           ```yaml
           ...
           ```
        2. curl command:
           ```bash
           curl -X POST ...
           ```
        3. Actual response / error:
           ```json
           ...
           ```
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant server logs
      render: text
      description: Paste any relevant log output here.

  - type: checkboxes
    id: checklist
    attributes:
      label: Before submitting
      options:
        - label: I have searched existing issues and this is not a duplicate.
          required: true
        - label: I am running a supported Go version (1.22+).
          required: true
